version: '3.8'

services:
  app:
    image: 1201q/coin:latest
    container_name: coin
    restart: always
    expose:
      - "8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
