version: "3.8"

services:
  app:
    image: 1201q/coin:latest
    container_name: coin
    restart: always
    expose:
      - "8000"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    platform: linux/arm64

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
    platform: linux/arm64

networks:
  app-network:
    driver: bridge
