name: coin
on:
  push:
    branches: ["main"]
    paths:
      - 'apps/server/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and release to DockerHub
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/coin:${{github.sha}} ./apps/server
          docker push ${{secrets.DOCKERHUB_USERNAME}}/coin:${{github.sha}}

      - name: Send files
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "nginx.conf,docker-compose.yml"
          target: /home/ubuntu/coin
          overwrite: true

      - name: Deploy to BE server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /home/ubuntu/coin
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/coin:${{github.sha}}
            
            envsubst < docker-compose.yml > docker-compose-processed.yml
            docker-compose -f docker-compose-processed.yml down
            docker-compose -f docker-compose-processed.yml up -d
            docker image prune -f
